const signet =  "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNXKK00000000KKXXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWX0kdlc:,'.....      .....',;cldk0XNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0xo:,..                               .':lx0NWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOo:'.                                          ..:okXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0d:.                   .....''''.....                   .:d0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMW0o;.             ..,:loxk0KKXXNNNNNNXXKK0Oxdl:,..             .,o0NMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMWXx;.           .':ok0XWMMMMMMMMMMMMMMMMMMMMMMMMMMWNKko:'.           .,dKWMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMW0l.          .'cx0NWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNKxl,.          .cONMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMWO:.         .;o0NMNKKKXNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0d;.         .;kNMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMWO:.         ,o0WMMMWd....xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKd;.         ;kNMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMWKc.        .cONMMMMMMWl    dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOc.        .:0WMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMNd.        .l0WMMMMMMMMWl   .dWMMMWWNNXXKKKKKKKKKKXXNNWWMMMMMMMMMMMMMMMMMMMMMWKo.        .oXMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMW0:        .lKWMMMMMMMMMMWl    ;olc:;,'................',;:codk0XWMMMMMMMMMMMMMMMWKo.        ;OWMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMWx.        :0WMMMMMMMMMWKko'                                     .,:okKWMMMMMMMMMMMMW0c.       .dNMMMMMMMMMMM\n" +
                "MMMMMMMMMMNo.       .xNMMMMMMMMMMWKxl:.                                          .;oONMMMMMMMMMMMWk'       .lXMMMMMMMMMM\n" +
                "MMMMMMMMMXl.       ;0WMMMMMMMMMMMMMMMWl    cOxo:'.                                   'o0WMMMMMMMMMMK:        cXMMMMMMMMM\n" +
                "MMMMMMMMXc       .lXMMMMMMMMMMMMMMMMMWl    dWMMMN0x:.                                  .c0WMMMMMMMMMNo.       :XMMMMMMMM\n" +
                "MMMMMMMNl       .oNMMMMMMMMMMMMMMMMMMWl    dWMMMMMMWKd'                                  .lXMMMMMMMMMNd.       cXMMMMMMM\n" +
                "MMMMMMWd.      .oNMMMMMMMMMMMMMMMMMMMWl    dWMMMMMMMMMXo.                                  ,OWMMMMMMMMWx.       oNMMMMMM\n" +
                "MMMMMMk.       lNMMMMMMMMMMMMMMMMMMMMWl    dWMMMMMMMMMMWk.                                  'OWMMMMMMMMNd.      .xWMMMMM\n" +
                "MMMMMX;       :XMMMMMMMMMMMMMMMMMMMMMWl    dWMMMMMMMMMMMWk.                                  '0MMMMMMMMMNc       ,KMMMMM\n" +
                "MMMMWd.      'OMMMMMMMMMMMMMMMMMMMMMMWl    dWMMMMMMMMMMMMNl                                   cNMMMMMMMMM0,       oWMMMM\n" +
                "MMMMK,       oWMMMMMMMMMMMMMMMMMMMMMMWl    dWMMMMMMMMMMMMMk.                                  .kMMMMMMMMMWd.      '0MMMM\n" +
                "MMMMx.      '0MMMMMMMMMMMMMMMMMMMMMMMWl    dWMMMMMMMMMMMMM0'                                   oWMMMMMMMMMK;       dWMMM\n" +
                "MMMNc       lWMMMMMMMMMMMMMMMMMMMMMMMWl    dWMMMMMMMMMMMMMK,                                   cNMMMMMMMMMWo       :XMMM\n" +
                "MMMK,      .kMMMMMMMMMMMMMMMMMMMMMMMMWl    dWMMMMMMMMMMMMM0'                                   cNMMMMMMMMMMO.      '0MMM\n" +
                "MMMO.      '0MMMMMMMMMMMMMMMMMMMMMMMMWl    dWMMMMMMMMMMMMMx.                                   oWMMMMMMMMMMK,      .kMMM\n" +
                "MMMk.      ;KMMMMMMMMMMMMMMMMMMMMMMMMWl    dWMMMMMMMMMMMMX;                                   '0MMMMMMMMMMMX:      .dWMM\n" +
                "MMMx.      ;XMMMMMMMMMMMMMMMMMMMMMMMMWl    dWMMMMMMMMMMMXl                                   .xWMMMMMMMMMMMNc       dWMM\n" +
                "MMMx.      ;XMMMMMMMMMMMMMMMMMMMMMMMMWl    dWMMMMMMMMMWKc                                   .xNMMMMMMMMMMMMN:      .dWMM\n" +
                "MMMk.      ,KMMMMMMMMMMMMMMMMMMMMMMMMWl    dWMMMMMMMMXd'                                  .c0WMMMMMMMMMMMMMX;      .xMMM\n" +
                "MMM0'      .OMMMMMMMMMMMMMMMMMMMMMMMMWl    dWMMMMMWKd'                                  .cOWMMMMMMMMMMMMMMM0'      .OMMM\n" +
                "MMMX;      .dWMMMMMMMMMMMMMMMMMMMMMMMWl    dWMMWKx:.                                .'cxXWMMMMMMMMMMMMMMMMMx.      ,KMMM\n" +
                "MMMWo       :XMMMMMMMMMMMMMMMMMMMMMMMWl    dNKd;.                              ..;ld0NWMMMMMMMMMMMMMMMMMMMNc       cNMMM\n" +
                "MMMMO.      .kMMMMMMMMMMMMMMMMMMMMMMMWl    ,;.                         ..';:ldk0XWMMMMMMMMMMMMMMMMMMMMMMMMO'      .kMMMM\n" +
                "MMMMNc       :XMMMMMMMMMMMMMMMMMMMMMMWl                   ...';:clodxk0KXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl       ;XMMMM\n" +
                "MMMMMO.      .dWMMMMMMMMMMMMMMMMMMMMMWl            .,:ldkOKXNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk.      .xMMMMM\n" +
                "MMMMMNo       'OWMMMMMMMMMMMMMMMMMMMMX:       .'cdOXNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0,       cNMMMMM\n" +
                "MMMMMMK;       ,0MMMMMMMMMMMMMMMMMMMWd.     'oONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK:       ,0MMMMMM\n" +
                "MMMMMMMO'       ;KMMMMMMMMMMMMMMMMMM0'    'xXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX:       .kWMMMMMM\n" +
                "MMMMMMMWk.       ,0WMMMMMMMMMMMMMMMMx.   cKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK:       .xWMMMMMMM\n" +
                "MMMMMMMMWk.       'kWMMMMMMMMMMMMMMWd.  :XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO,       .xWMMMMMMMM\n" +
                "MMMMMMMMMWO'       .oXMMMMMMMMMMMMMMx. .OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNd.       .xWMMMMMMMMM\n" +
                "MMMMMMMMMMW0;        ;OWMMMMMMMMMMMMO. :XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0:        ,OWMMMMMMMMMM\n" +
                "MMMMMMMMMMMMXl.       .lKWMMMMMMMMMMN: lWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXo.        cKMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMNx'        .oKWMMMMMMMMMk'lWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXd'        .dNMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMWKl.        .l0WMMMMMMMNllNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKo'        .c0WMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMWO:         .:kXMMMMMMKdKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOc.         ;kWMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMNk;.         'lONMMMWKXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOo,          ,xNMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMNO:.          'cxKWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXkl'.         .;kNMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMW0l'           .,lx0NWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKxl;.           .lOWMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMXx:.            .';ldk0XNWMMMMMMMMMMMMMMMMMMWNXKOdl:'.            .:xXWMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMWKxc.               ..';:clooddxxxxxddolc:;'..               .:dKWMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOo;.                                                .;lkXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOo:'.                                      .':okKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNKOdl:,..                        ..,:ldkKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXK0kxoolcc::;;;;::ccloodkOKXWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n"
export default signet
